---
- hosts: {{ cookiecutter.project_name }}
  # Prevent error occurs before pre_tasks. (ex. Docker container isn't running.)
  gather_facts: no
  pre_tasks:
    - set_fact:
        utility_module_path: "{{ '{{ utility_module_path|default(\'../../ansible_utility\') }}' }}"
    - name: Do pre-task for each platform
      include: "{{ '{{ utility_module_path }}' }}/pre_tasks/{{ '{{ ansible_connection }}' }}.yml"
    - name: "Gather fact information on target platform."
      setup:
  roles:
    # - role: FGtatsuro.python-requirements
  tasks:
    - block:
      - name: Ensure /opt/{{ cookiecutter.project_name }} directory exists
        file:
          path: '/opt/{{ cookiecutter.project_name }}'
          owner: 'root'
          group: 'root'
          state: 'directory'
      - name: Set service script
        template:
          src: '../resources/services.sh'
          dest: '/opt/{{ cookiecutter.project_name }}/services.sh'
          mode: '0755'
      become: yes
  post_tasks:
    - name: Do post-task for each platform
      include: "{{ '{{ utility_module_path }}' }}/post_tasks/{{ '{{ ansible_connection }}' }}.yml"
