---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip

sudo: required

install:
  - pip install cookiecutter

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - git clone https://github.com/FGtatsuro/ansible_utility.git
  - cd test_project
  - pip install ansible
  # ansible-galaxy CLI returns error status when no rule exists in requirement file.
  # - ansible-galaxy install -r role_requirements.yml
  - gem install bundler
  - bundle install
  - ansible-playbook provision/main.yml -i spec/inventory/docker/hosts -l test_project
  - docker rm -f test_project-spec
  - (cd deploy/docker/ && docker-compose up -d)
  - bundle exec rake test_project:spec:all
  - (cd deploy/docker/ && docker-compose down)
