---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip

sudo: required

install:
  - pip install cookiecutter

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd test_project
  - pip install ansible
  - ansible-galaxy install -r role_requirements.yml
  - gem install bundler
  - bundle install
  - ansible-playbook provision/main.yml -i spec/inventory/docker/hosts -l test_project
  - bundle exec rake spec:test_project:all
