---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
os: linux
dist: trusty
language: python
python: 2.7
services:
  - docker
addons:
  apt:
    packages:
      - python-pip

sudo: required

install:
  - pip install cookiecutter

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - git clone https://github.com/FGtatsuro/ansible_utility.git
  - cd test_project
  - pip install ansible
  # ansible-galaxy CLI returns error status when no rule exists in requirement file.
  # - ansible-galaxy install -r role_requirements.yml
  - gem install bundler
  - bundle install
  - ansible-playbook provision/main.yml -i tests/inventory/docker/hosts -l test_project -vvvv
  - docker rm -f service-test_project
  - bundle exec rake test_project:gen-start-cmd
  - bundle exec rake test_project:start
  - bundle exec rake test_project:spec:all
  - bundle exec rake test_project:gen-stop-cmd
  - bundle exec rake test_project:stop
  - bundle exec rake test_project:gen-pull-cmd
