---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
      install:
        - sudo pip install -U setuptools
        - sudo pip install cookiecutter
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container python:2 /bin/bash
        # Workaround: Docker connection plugin of Ansible requires that
        # Python is installed at specified path(/usr/bin/python) in the target container
        - docker exec container /bin/bash -c "if [ ! -e /usr/bin/python -a -e /usr/local/bin/python ]; then /bin/ln -s /usr/local/bin/python /usr/bin/python; fi"
      after_script:
        - docker rm -f container
      env:
        - TARGET=container

sudo: required

install:
  - pip install cookiecutter

script:
  - cookiecutter --replay --config-file tests/cookiecutterrc .
  - cd test_project
  # TODO: Do something
  - bundle install
  - bundle exec rake spec SPEC_TARGET=${TARGET}
