---
branches:
  only:
  - master

os: linux
dist: trusty
language: python
python: 2.7
services:
  - docker
addons:
  apt:
    packages:
      - python-pip

sudo: required

install:
  - pip install ansible
  # ansible-galaxy CLI returns error status when no rule exists in requirement file.
  # - ansible-galaxy install -r role_requirements.yml
  - gem install bundler
  - bundle install

script:
  - git clone https://github.com/FGtatsuro/ansible_utility.git
  - ansible-playbook provision/main.yml -i spec/inventory/docker/hosts -l {{ cookiecutter.project_name }} --extra-vars="utility_module_path=../ansible_utility" -vvvv
  - docker rm -f service-{{ cookiecutter.project_name }}
  - bundle exec rake {{ cookiecutter.project_name }}:gen-start-cmd
  - bundle exec rake {{ cookiecutter.project_name }}:start
  - bundle exec rake {{ cookiecutter.project_name }}:spec:all
  - bundle exec rake {{ cookiecutter.project_name }}:gen-stop-cmd
  - bundle exec rake {{ cookiecutter.project_name }}:stop
