require 'rake'
require 'rspec/core/rake_task'

namespace '{{ cookiecutter.project_name }}' do
  namespace :spec do
    hosts = [
      {
        :name     =>  'service-{{ cookiecutter.project_name }}',
        :backend  =>  'docker',
        :pattern  =>  "{{ cookiecutter.project_name }}_spec.rb"
      }
    ]

    all = []

    hosts.each do |host|
      n = host[:name].gsub(/service-/, '')
      desc "Run serverspec tests for #{n}."
      RSpec::Core::RakeTask.new(n.to_sym) do |t|
        ENV['TARGET_HOST'] = host[:name]
        ENV['TARGET_BACKEND'] = host[:backend]
        t.pattern = host[:pattern]
      end
      all << "{{ cookiecutter.project_name }}:spec:#{n}"
    end

    task :all =>  all
  end
end
